imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_addressing:
    resources:
        address:
            classes:
                model: App\Entity\Sylius\Addressing\Address
        country:
            classes:
                model: App\Entity\Sylius\Addressing\Country
        province:
            classes:
                model: App\Entity\Sylius\Addressing\Province
        zone:
            classes:
                model: App\Entity\Sylius\Addressing\Zone
        zone_member:
            classes:
                model: App\Entity\Sylius\Addressing\ZoneMember

sylius_admin_api:
    resources:
        api_client:
            classes:
                model: App\Entity\Sylius\AdminApi\Client
        api_access_token:
            classes:
                model: App\Entity\Sylius\AdminApi\AccessToken
        api_refresh_token:
            classes:
                model: App\Entity\Sylius\AdminApi\RefreshToken
        api_auth_code:
            classes:
                model: App\Entity\Sylius\AdminApi\AuthCode

sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: App\Entity\Sylius\Product\ProductAttribute
                translation:
                    classes:
                        model: App\Entity\Sylius\Product\ProductAttributeTranslation
            attribute_value:
                classes:
                    model: App\Entity\Sylius\Product\ProductAttributeValue

sylius_channel:
    resources:
        channel:
            classes:
                model: App\Entity\Sylius\Channel\Channel
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\Sylius\Product\ProductImage
        taxon_image:
            classes:
                model: App\Entity\Sylius\Taxonomy\TaxonImage
        product_taxon:
            classes:
                model: App\Entity\Sylius\Product\ProductTaxon
        channel_pricing:
            classes:
                model: App\Entity\Sylius\Channel\ChannelPricing

sylius_currency:
    resources:
        currency:
            classes:
                model: App\Entity\Sylius\Currency\Currency
        exchange_rate:
            classes:
                model: App\Entity\Sylius\Currency\ExchangeRate

sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\Sylius\Customer\Customer
        customer_group:
            classes:
                model: App\Entity\Sylius\Customer\CustomerGroup

sylius_locale:
    resources:
        locale:
            classes:
                model: App\Entity\Sylius\Locale\Locale

sylius_order:
    resources:
        order:
            classes:
                model: App\Entity\Sylius\Order\Order
        order_item:
            classes:
                model: App\Entity\Sylius\Order\OrderItem
        order_item_unit:
            classes:
                model: App\Entity\Sylius\Order\OrderItemUnit
        adjustment:
            classes:
                model: App\Entity\Sylius\Order\Adjustment
        order_sequence:
            classes:
                model: App\Entity\Sylius\Order\OrderSequence

sylius_payment:
    resources:
        payment_method:
            classes:
                model: App\Entity\Sylius\Payment\PaymentMethod
            translation:
                classes:
                    model: App\Entity\Sylius\Payment\PaymentMethodTranslation
        payment:
            classes:
                model: App\Entity\Sylius\Payment\Payment

sylius_payum:
    resources:
        payment_security_token:
            classes:
                model: App\Entity\Sylius\Payment\PaymentSecurityToken
        gateway_config:
            classes:
                model: App\Entity\Sylius\Payment\GatewayConfig

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Sylius\Product\Product
            translation:
                classes:
                    model: App\Entity\Sylius\Product\ProductTranslation
        product_variant:
            classes:
                model: App\Entity\Sylius\Product\ProductVariant
            translation:
                classes:
                    model: App\Entity\Sylius\Product\ProductVariantTranslation
        product_option:
            classes:
                model: App\Entity\Sylius\Product\ProductOption
            translation:
                classes:
                    model: App\Entity\Sylius\Product\ProductOptionTranslation
        product_option_value:
            classes:
                model: App\Entity\Sylius\Product\ProductOptionValue
            translation:
                classes:
                    model: App\Entity\Sylius\Product\ProductOptionValueTranslation
        product_association:
            classes:
                model: App\Entity\Sylius\Product\ProductAssociation
        product_association_type:
            classes:
                model: App\Entity\Sylius\Product\ProductAssociationType
            translation:
                classes:
                    model: App\Entity\Sylius\Product\ProductAssociationTypeTranslation

sylius_promotion:
    resources:
        promotion:
            classes:
                model: App\Entity\Sylius\Promotion\Promotion
        promotion_rule:
            classes:
                model: App\Entity\Sylius\Promotion\PromotionRule
        promotion_action:
            classes:
                model: App\Entity\Sylius\Promotion\PromotionAction
        promotion_coupon:
            classes:
                model: App\Entity\Sylius\Promotion\PromotionCoupon

sylius_review:
    resources:
        product:
            review:
                classes:
                    model: App\Entity\Sylius\Product\ProductReview

sylius_shipping:
    resources:
        shipment:
            classes:
                model: App\Entity\Sylius\Shipping\Shipment
        shipping_method:
            classes:
                model: App\Entity\Sylius\Shipping\ShippingMethod
            translation:
                classes:
                    model: App\Entity\Sylius\Shipping\ShippingMethodTranslation
        shipping_category:
            classes:
                model: App\Entity\Sylius\Shipping\ShippingCategory

sylius_taxation:
    resources:
        tax_category:
            classes:
                model: App\Entity\Sylius\Taxation\TaxCategory
        tax_rate:
            classes:
                model: App\Entity\Sylius\Taxation\TaxRate

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: App\Entity\Sylius\Taxonomy\Taxon
            translation:
                classes:
                    model: App\Entity\Sylius\Taxonomy\TaxonTranslation
sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: App\Entity\Sylius\User\AdminUser
        shop:
            user:
                classes:
                    model: App\Entity\Sylius\User\ShopUser
        oauth:
            user:
                classes:
                    model: App\Entity\Sylius\User\UserOAuth

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"
