sylius_grid:
    grids:
        app_admin_price:
            driver:
                options:
                    class: '%app.model.price.class%'
            sorting:
                cooperative: desc
                price: asc
            fields:
                id:
                    type: string
                    label: app.ui.id
                cooperative:
                    type: string
                    sortable: ~
                customField:
                    type: string
                    path: randomData
                status:
                    type: string
                price:
                    type: twig
                    options:
                        template: 'Admin/Price/Grid/priceField.html.twig'
                    sortable: ~
            filters:
                search:
                    type: string
                    options:
                        fields: [cooperative]
            actions:
                main:
                    google:
                        type: create
                        options:
                            link:
                                url: http://google.com
                    product:
                        type: create
                        options:
                            link:
                                path: sylius_admin_product_index
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    approve:
                        type: apply_transition
                        options:
                            transition: approve
                            graph: app_price
                            link:
                                route: app_admin_price_approve
                                parameters:
                                    id: resource.id
                        label: approve
                    outdate:
                        type: apply_transition
                        options:
                            transition: outdate
                            graph: app_price
                            link:
                                route: app_admin_price_outdate
                                parameters:
                                    id: resource.id
                        label: outdate
                    recreate:
                        type: apply_transition
                        options:
                            transition: recreate
                            graph: app_price
                            link:
                                route: app_admin_price_recreate
                                parameters:
                                    id: resource.id
                        label: recreate
