sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_admin_price:
    resource: | # hack to treat array of configuration as one string for Symfony
        alias: app.price
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: [show]
        redirect: update
        grid: app_admin_price
        vars:
            create:
                header: Custom header
    type: sylius.resource
    prefix: /admin

app_admin_price_approve:
    methods: ['PUT']
    path: '/admin/prices/{id}/approve'
    defaults:
        _controller: app.controller.price:applyStateMachineTransitionAction
        _sylius:
            section: admin
            state_machine:
                graph: app_price
                transition: approve

app_admin_price_outdate:
    methods: ['PUT']
    path: '/admin/prices/{id}/outdate'
    defaults:
        _controller: app.controller.price:applyStateMachineTransitionAction
        _sylius:
            section: admin
            state_machine:
                graph: app_price
                transition: outdate

app_admin_price_recreate:
    methods: ['PUT']
    path: '/admin/prices/{id}/recreate'
    defaults:
        _controller: app.controller.price:applyStateMachineTransitionAction
        _sylius:
            section: admin
            state_machine:
                graph: app_price
                transition: recreate
